apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app: argocd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
        - name: argocd-server
          image: argoproj/argocd:v2.3.2
          ports:
            - containerPort: 8080
          env:
            - name: ARGOCD_SERVER_INSECURE
              value: "true"
          volumeMounts:
            - name: argocd-config
              mountPath: /etc/argocd
      volumes:
        - name: argocd-config
          configMap:
            name: argocd-config
