apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8080
      nodePort: 30008
      protocol: TCP
      name: https
  selector:
    app: argocd-server
